.PHONY: clean All

All:
	@echo "----------Building project:[ EpsilonObject - Debug ]----------"
	@$(MAKE) -f  "EpsilonObject.mk"
clean:
	@echo "----------Cleaning project:[ EpsilonObject - Debug ]----------"
	@$(MAKE) -f  "EpsilonObject.mk" clean
